name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: DigitalAudioExperiment.sln
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build the application
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ env.Configuration }} --output BuildOutput

    - name: List build outputs
      shell: pwsh
      run: |
        Get-ChildItem -Path "BuildOutput/**/*" -Recurse | ForEach-Object { Write-Host $_.FullName }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DigitalAudioExperiment
        path: 'BuildOutput/**/*'
